[package]
name = "tc-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1"
futures = "0.3"
destream = { path = "../deps/destream", version = "0.10" }
destream_json = { path = "../deps/destream_json", version = "0.15" }
pathlink = { path = "../deps/pathlink" }
serde = { version = "1", features = ["derive"] }
tc-error = { path = "../tc-error" }
tc-ir = { path = "../tc-ir" }
tc-value = { path = "../tc-value" }
umask = "2.1"
